name: Vulnerability Report in PR Comments and Issues

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build an image from Dockerfile
      run: |
        docker build -t trivy-test:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner with SARIF output
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'config'
        format: 'sarif'
        vuln-type: 'os,library'
        severity: 'HIGH,CRITICAL'
        output: 'trivy-config-results.sarif'

    - name: Run Trivy vulnerability scanner with SARIF output
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'trivy-test:${{ github.sha }}'
        format: 'sarif'
        vuln-type: 'os,library'
        severity: 'HIGH,CRITICAL'
        output: 'trivy-image-results.sarif'

    - name: Display contents of trivy-image-results.sarif
      run: cat trivy-image-results.sarif

    - name: Upload SARIF Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-config-results.sarif'

    - name: Display contents of trivy-image-results.sarif
      run: cat trivy-config-results.sarif

    - name: Upload SARIF Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-image-results.sarif'

