name: Vulnerability Report in Security Tab and PR

on:
  pull_request:
    branches:
      - main
    types:
      - synchronize

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build an image from Dockerfile
      run: |
        docker build -t trivy-test:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner in table format
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'trivy-test:${{ github.sha }}'
        format: 'table'
        vuln-type: 'os,library'
        severity: 'HIGH,CRITICAL'
        output: 'trivy-results.txt'

    # PRのコメント部分に脆弱性のスキャン結果を追加
    - name: Comment PR with Trivy scan results
      uses: actions/github-script@v3
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        script: |
          const fs = require('fs');
          const output = fs.readFileSync('trivy-results.txt', 'utf8');
          const issue_number = context.issue.number;
          const message = ` **Trivy Vulnerability Scan Results** \n\n\`\`\`\n${output}\n\`\`\`\nPlease review the vulnerabilities and take necessary actions.`;
          github.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });

    # ISSUEに脆弱性のスキャン結果を追加
    - name: Create GitHub Issue from Trivy scan results
      uses: knqyf263/trivy-issue-action@main
      with:
        severity: 'HIGH,CRITICAL'
        label: 'vulnerability'
      env:
        GH_TOKEN: ${{ steps.generate_token.outputs.token }}
