name: CI/CD with Vulnerability Scanning

on:
  pull_request:
    branches:
      - main
    types:
      # PR更新時に実行
      - synchronize

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build an image from Dockerfile
      run: |
        docker build -t trivy-test:${{ github.sha }} .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@v0.0.20 
      with:
        image-ref: 'trivy-test:${{ github.sha }}'
        format: 'json'
        # output: 'trivy-results.json'
        vuln-type: 'os,library'
        severity: 'LOW,MEDIUM,HIGH,CRITICAL'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    # - name: Create GitHub Issue from Trivy scan results
    #   uses: knqyf263/trivy-issue-action@main
    #   with:
    #     severity: 'HIGH,CRITICAL'
    #     label: 'vulnerability'
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # ISSUEへの書き込み
    # - name: Run Trivy vulnerability scanner and create GitHub Issue
    #   uses: lazy-actions/gitrivy@main
    #   with:
    #     image: 'trivy-test:latest'
    #     # severity: 'HIGH,CRITICAL'
    #     vuln_type: 'os,library'
    #     token: ${{ secrets.GITHUB_TOKEN }}
