name: CI/CD with Vulnerability Scanning2

on:
  pull_request:
    branches:
      - main
    types:
      # PR更新時に実行
      - synchronize

env:
  TRIVY_VERSION: 0.44.1

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
      issues: write

    steps:

    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build an image from Dockerfile
      run: |
        docker build -t trivy-test:${{ github.sha }} .


    - name: Install Trivy
      run: |
        sudo apt-get install rpm
        wget https://github.com/aquasecurity/trivy/releases/download/v${{ env.TRIVY_VERSION }}/trivy_${{ env.TRIVY_VERSION }}_Linux-64bit.deb
        sudo dpkg -i trivy_${{ env.TRIVY_VERSION }}_Linux-64bit.deb

    - name: Run Trivy vulnerability scanner on Terraform config
      run: |
        trivy config --debug --severity HIGH,CRITICAL . > trivy-result.txt

    - name: Upload Trivy scan results
      uses: actions/upload-artifact@v2
      with:
        name: trivy-result
        path: trivy-result.txt

    - name: Comment PR with Trivy scan results
      uses: actions/github-script@v3
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        script: |
          const fs = require('fs');
          const output = fs.readFileSync('trivy-result.txt', 'utf8');
          const issue_number = context.issue.number;
          const message = `### Trivy Vulnerability Scan Results:\n\`\`\`${output}\`\`\``;
          github.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });

