name: CI/CD with Vulnerability Scanning

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t my-app:latest .

    - name: Install Trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.deb
        sudo dpkg -i trivy_0.19.2_Linux-64bit.deb

    - name: Run Trivy vulnerability scanner
      run: |
        trivy image --format template --template "@/contrib/sarif.tpl" my-app:latest > trivy-results.sarif

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: trivy-results.sarif
