name: CI/CD with Vulnerability Scanning

# トリガー設定
on:
  pull_request:
    branches:
      - main
    types:
      - synchronize # PRが更新されたときに実行

env:
  TRIVY_VERSION: 0.44.1

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
      issues: write

    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build an image from Dockerfile
      run: |
        docker build -t trivy-test:${{ github.sha }} .

    - name: Install Trivy
      run: |
        sudo apt-get install rpm
        wget https://github.com/aquasecurity/trivy/releases/download/v${{ env.TRIVY_VERSION }}/trivy_${{ env.TRIVY_VERSION }}_Linux-64bit.deb
        sudo dpkg -i trivy_${{ env.TRIVY_VERSION }}_Linux-64bit.deb

    - name: Run Trivy vulnerability scanner on Terraform config
      run: |
        trivy config --severity HIGH,CRITICAL . > trivy-config-scan-result.txt
        trivy image --severity HIGH,CRITICAL trivy-test:${{ github.sha }} > trivy-image-scan-result.txt

    # PRにTrivyコンフィグスキャン結果をコメント
    - name: Comment PR with Trivy config scan results
      uses: actions/github-script@v3
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        script: |
          const fs = require('fs');
          const output = fs.readFileSync('trivy-config-scan-result.txt', 'utf8');
          const issue_number = context.issue.number;
          const message = `## Trivy Config Vulnerability Scan Results \n\n\`\`\`\n${output}\n\`\`\``;
          github.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });

    # PRにTrivyイメージスキャン結果をコメント
    - name: Comment PR with Trivy image scan results
      uses: actions/github-script@v3
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        script: |
          const fs = require('fs');
          const output = fs.readFileSync('trivy-image-scan-result.txt', 'utf8');
          const issue_number = context.issue.number;
          const message = `## Trivy Image Vulnerability Scan Results \n\n\`\`\`\n${output}\n\`\`\``;
          github.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
